// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	SendMessage(ctx context.Context, in *ReqMessage, opts ...grpc.CallOption) (*RplMessage, error)
	StreamVideo(ctx context.Context, opts ...grpc.CallOption) (Service_StreamVideoClient, error)
	StreamAudio(ctx context.Context, opts ...grpc.CallOption) (Service_StreamAudioClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) SendMessage(ctx context.Context, in *ReqMessage, opts ...grpc.CallOption) (*RplMessage, error) {
	out := new(RplMessage)
	err := c.cc.Invoke(ctx, "/protobuf.Service/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) StreamVideo(ctx context.Context, opts ...grpc.CallOption) (Service_StreamVideoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[0], "/protobuf.Service/StreamVideo", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceStreamVideoClient{stream}
	return x, nil
}

type Service_StreamVideoClient interface {
	Send(*VideoChunk) error
	CloseAndRecv() (*ReceiveReply, error)
	grpc.ClientStream
}

type serviceStreamVideoClient struct {
	grpc.ClientStream
}

func (x *serviceStreamVideoClient) Send(m *VideoChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceStreamVideoClient) CloseAndRecv() (*ReceiveReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReceiveReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) StreamAudio(ctx context.Context, opts ...grpc.CallOption) (Service_StreamAudioClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[1], "/protobuf.Service/StreamAudio", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceStreamAudioClient{stream}
	return x, nil
}

type Service_StreamAudioClient interface {
	Send(*AudioChunk) error
	CloseAndRecv() (*ReceiveReply, error)
	grpc.ClientStream
}

type serviceStreamAudioClient struct {
	grpc.ClientStream
}

func (x *serviceStreamAudioClient) Send(m *AudioChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceStreamAudioClient) CloseAndRecv() (*ReceiveReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReceiveReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	SendMessage(context.Context, *ReqMessage) (*RplMessage, error)
	StreamVideo(Service_StreamVideoServer) error
	StreamAudio(Service_StreamAudioServer) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) SendMessage(context.Context, *ReqMessage) (*RplMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedServiceServer) StreamVideo(Service_StreamVideoServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamVideo not implemented")
}
func (UnimplementedServiceServer) StreamAudio(Service_StreamAudioServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Service/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SendMessage(ctx, req.(*ReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_StreamVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).StreamVideo(&serviceStreamVideoServer{stream})
}

type Service_StreamVideoServer interface {
	SendAndClose(*ReceiveReply) error
	Recv() (*VideoChunk, error)
	grpc.ServerStream
}

type serviceStreamVideoServer struct {
	grpc.ServerStream
}

func (x *serviceStreamVideoServer) SendAndClose(m *ReceiveReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceStreamVideoServer) Recv() (*VideoChunk, error) {
	m := new(VideoChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Service_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).StreamAudio(&serviceStreamAudioServer{stream})
}

type Service_StreamAudioServer interface {
	SendAndClose(*ReceiveReply) error
	Recv() (*AudioChunk, error)
	grpc.ServerStream
}

type serviceStreamAudioServer struct {
	grpc.ServerStream
}

func (x *serviceStreamAudioServer) SendAndClose(m *ReceiveReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceStreamAudioServer) Recv() (*AudioChunk, error) {
	m := new(AudioChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Service_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamVideo",
			Handler:       _Service_StreamVideo_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamAudio",
			Handler:       _Service_StreamAudio_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/media.proto",
}
